# version: docker/dockerfile:1.7-labs

services:
  recorder:
    environment:
      - ASPNETCORE_HTTP_PORTS=5123
      # - ASPNETCORE_HTTPS_PORTS=7094
    ports:
      # props/launchsettings
      # iis settings
      # - 22845
      # - 44398
      # swagger https(part1)
      - 7094:7094
      # swagger http
      - 5123:5123
    #privileged: true
    # devices:
    #   - /dev/gpiomem
    # volumes:
    #   - /sys/class/gpio:/sys/class/gpio
    #   - /sys:/sys
    image: gardensage-recorder
    build:
      context: ..
      dockerfile: GardenSage.Recorder/Dockerfile
  #
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      # MUST RUN LINUX OR WSL
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro # optional; req for bluetooth
      # - ./wslconf:/config
    privileged: true
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 8123:8123
    # host.docker.internal:8123
