# version: docker/dockerfile:1.7-labs

services:
  recorder:
    environment:
      - ASPNETCORE_HTTP_PORTS=5123
      # - ASPNETCORE_HTTPS_PORTS=7094
    ports:
      # props/launchsettings
      # iis settings
      # - 22845
      # - 44398
      # swagger https(part1)
      - 7094:7094
      # swagger http
      - 5123:5123
    #privileged: true
    # devices:
    #   - /dev/gpiomem
    # volumes:
    #   - /sys/class/gpio:/sys/class/gpio
    #   - /sys:/sys
    image: gardensage-recorder
    build:
      context: ..
      dockerfile: GardenSage.Recorder/Dockerfile
  #
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      # MUST RUN LINUX OR WSL
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro # optional; req for bluetooth
      # https://sequr.be/blog/2022/11/home-assistant-container-part-11-bluetooth-support/#:~:text=To%20then%20get%20Home%20Assistant%20to%20recognize%20your,Assistant%20container%20by%20running%20docker-compose%20up%20-d%20homeassistant.
      # host: sudo apt install dbus-broker
      # sudo systemctl enable dbus-broker.service
      #  sudo apt install bluez
      - ./haconfig:/config
      # - /wslbind.txt:/wslbindup.txt:ro # (it does bind correctly on wsl, which confirms docker binds linux-style)
      - ./ha_configuration.yaml:/config/configuration.yaml
      - ./ha_automations.yaml:/config/automations.yaml
      - ./ha_scripts.yaml:/config/scripts.yaml
    privileged: true
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 8123:8123
    # host.docker.internal:8123
